---
- name: Deploy Virtual Machine on ESXi
  hosts: myhosts
  gather_facts: False
  tasks:
    - name: Create a virtual machine
      community.vmware.vmware_guest:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_private_key_file }}"
        validate_certs: no
        folder: "/vm"
        name: "new_vm"
        state: poweredon
        template: "template_name"
        disk:
          - size_gb: 20
            type: thin
        networks:
          - name: "network_name"
      environment:
        PYTHONPATH: "/usr/lib/python3/dist-packages"
