# Scenario 2
x-info: Web Security Testing Lab (DVWA, Juice Shop)

services:
  router:
    image: ghcr.io/0nano/router-alpine:latest
    hostname: router1
    privileged: true
    environment: 
      NAT: "true" 
    networks:
      internet-access:
        ipv4_address: 10.0.2.254 
        priority: 1000
      private-net:
        ipv4_address: 10.1.2.254 
        priority: 200

  Kali:
    image: ghcr.io/0nano/kali-web-simplify:latest
    hostname: kali
    x-inscription: 10.1.2.5
    networks:
      private-net:
        ipv4_address: 10.1.2.5 # a modifi pour pas empiter sur le reseau du scenario1 

  # dvwa:
  #   image: ghcr.io/guillaumerobin9/dvwa:latest 
  #   hostname: dvwa
  #   x-inscription: 10.1.2.6 
  #   networks:
  #     private-net:
  #       ipv4_address: 10.1.2.6 
    
  own-web-server:
    image: ghcr.io/guillaumerobin9/own-web-server:latest
    hostname: own-web-server
    x-inscription: 10.1.2.7
    networks:
      private-net:
        ipv4_address: 10.1.2.7

  juice-shop:
    image: ghcr.io/guillaumerobin9/juice-shop:latest
    hostname: juice-shop
    x-inscription: 10.1.2.6
    networks:
      private-net:
        ipv4_address: 10.1.2.6

  # mysql:
  #   image: ghcr.io/guillaumerobin9/mysql:latest
  #   hostname: mysql
  #   x-inscription: 10.1.2.8
  #   networks:
  #     private-net:
  #       ipv4_address: 10.1.2.8

networks:
  internet-access:
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24 
  private-net:
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.1.2.0/24 
