# Scenario 2

services:
  router:
    image: ghcr.io/0nano/router-alpine:latest
    hostname: router1
    privileged: true
    environment: 
      NAT: "true" 
    networks:
      internet-access:
        ipv4_address: 10.0.2.254 
        priority: 1000
      private-net:
        ipv4_address: 10.1.2.254 
        priority: 200

  # apache:
  #   image: httpd:2.4
  #   hostname: apache
  #   ports:
  #     - "8080:80"
  #   networks:
  #     private-net:
  #       ipv4_address: 10.1.2.5 

  Kali:
    image: ghcr.io/0nano/kali-web-simplify:latest
    hostname: kali
    networks:
      private-net:
        ipv4_address: 10.1.2.5 # a modifi pour pas empiter sur le reseau du scenario1 

  juice-shop:
    image: ghcr.io/guillaumerobin9/juice-shop:latest
    ports:
      - "3000:3000" # attention need ajout security group port 3000 popur y acceder depuis http (maybe aps besoin pour guaca a tester)
    networks:
      private-net:
        ipv4_address: 10.1.2.6 
    
  dvwa:
    image: ghcr.io/guillaumerobin9/dvwa:latest
    ports:
      - "4500:4500"
    networks:
      private-net:
        ipv4_address: 10.1.2.7

  # own-web-server:
  #   image: ghcr.io/guillaumerobin9/own-web-server:latest
  #   ports:
  #     - "3500:3500"
  #   networks:
  #     private-net:
  #       ipv4_address: 10.1.2.8


networks:
  internet-access:
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24 
  private-net:
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.1.2.0/24 
