# Scenario 1

services:
  router:
    image: ghcr.io/0nano/router-alpine:latest
    hostname: router1
    privileged: true
    environment: 
      NAT: true 
    networks:
      internet-access:
        ipv4_address: 10.0.1.254
        priority: 1000
      private-net:
        ipv4_address: 10.1.1.254
        priority: 200

  ftp-server:
    image: ghcr.io/0nano/ftp-alpine:latest
    hostname: ftp-server
    networks:
      private-net:
        ipv4_address: 10.1.1.3

  alpine-ssh:
    image: ghcr.io/0nano/alpine-sshd:latest
    hostname: apline
    networks:
      private-net:
        ipv4_address: 10.1.1.2

  Kali:
    image: ghcr.io/0nano/kali-web-simplify:latest
    hostname: kali
    networks:
      private-net:
        ipv4_address: 10.1.1.4

networks:
  internet-access:
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  private-net:
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24