---
- name: Main playbook for the scenario creation
  hosts: all
  tasks:

    - name: Vérifier si le playbook de création du serveur Guacamole existe
      stat:
        path: create_a_guacamole_bastion.yml
      register: create_a_guacamole_bastion

    - name: Exécuter create_a_guacamole_bastion.yml s'il existe
      include_tasks: create_a_guacamole_bastion.yml
      when: create_a_guacamole_bastion.stat.exists

    - name: Afficher un message d'erreur si create_a_guacamole_bastion.yml n'existe pas
      debug:
        msg: "create_a_guacamole_bastion.yml non trouvé"
      when: not create_a_guacamole_bastion.stat.exists

    # Serveur BDD
    - name: Vérifier si le playbook de création du serveur de base de données existe
      stat:
        path: create_a_bdd_server.yml
      register: create_a_bdd_server

    - name: Exécuter create_a_bdd_server.yml s'il existe
      include_tasks: create_a_bdd_server.yml
      when: create_a_bdd_server.stat.exists

    - name: Afficher un message d'erreur si create_a_bdd_server.yml n'existe pas
      debug:
        msg: "create_a_bdd_server.yml non trouvé"
      when: not create_a_bdd_server.stat.exists

    # Serveur FTP
    - name: Vérifier si le playbook de création du serveur FTP existe
      stat:
        path: ftp_serv.yml
      register: ftp_serv

    - name: Exécuter ftp_serv.yml s'il existe
      include_tasks: ftp_serv.yml
      when: ftp_serv.stat.exists

    - name: Afficher un message d'erreur si ftp_serv.yml n'existe pas
      debug:
        msg: "ftp_serv.yml non trouvé"
      when: not ftp_serv.stat.exists
