// automate deployement of SES Amazon Simple Email Service 

---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3 
    region: us-east-1
    instance_type: t2.micro
    key_name: vockey # Change for your key pair
    sec_group: "test-security-group"
    #image_id: ami-0005e0cfe09cc9050 # Latest version of Amazon Linux
    image_id: ami-058bd2d568351da34 # Debian 12 OS
    guacamole_docker_repo: "https://github.com/boschkundendienst/guacamole-docker-compose.git"
    default_container_name: guacamole_docker
    default_container_image: guacamole/guacd
  tasks:
    - name: Create a security group
      amazon.aws.ec2_security_group:
        name: "{{ sec_group }}"
        description: "Allow SSH and HTTP"
        region: "{{ region }}"
        rules: 
          - proto: tcp
            ports:
              - 22
              - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow ssh and http

    - name: Start an instance and add EBS
      amazon.aws.ec2_instance:
        name: "SES"    
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ sec_group }}"
        key_name: "{{ key_name }}"
        image_id: "{{ image_id }}"
        termination_protection: true # because if not the EC2 instance will be terminated after playbook run
        state: running
      register: ec2
      #   tags:
      #     Environment: Bastion testing
      # tags: ['never', 'create_ec2_instance']

    - name: Facts
      block: # this block prints out instance data

      - name: Get instances facts
        ec2_instance_info:
          region: "{{ region }}"
        register: result

      - name: Instances ID
        debug:
          msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
        loop: "{{ result.instances }}"
      tags: always

    - name: "Add new Instance to Host group"
      add_host:
        hostname: "{{ ec2.instances.0.public_ip_address }}"
        groupname: webserver

    - name: "Wait for SSH in Instance"
      wait_for:
        host: "{{ ec2.instances.0.public_ip_address }}"
        port: 22  
