---
- hosts: localhost
  vars:
    region: us-east-1
  tasks:
    - name: create a VPC
      amazon.aws.ec2_vpc_net:
        name: <Your-VPC-Name>
        aws_access_key: "{{ ec2_access_key }}"  # From vault
        aws_secret_key: "{{ ec2_secret_key }}"  # From vault
        # aws_session_token: "{{ ec2_session_token }}" # From vault, it's very important to add this line to use temporary credentials
        cidr_block: 10.0.0.0/16
        region: "{{ region }}"
        tags:
          module: ec2_vpc_net
          this: works