---
- hosts: localhost
  vars:
    region: us-east-1
  tasks:
    - name: "Create a IGW for a VPC"
      amazon.aws.ec2_vpc_igw:
        vpc_id: vpc-12345678
        aws_access_key: "{{ ec2_access_key }}"  # From vault
        aws_secret_key: "{{ ec2_secret_key }}"  # From vault
        # aws_session_token: "{{ ec2_session_token }}" # From vault, it's very important to add this line to use temporary credentials
        state: present