# Scenario 3
x-info: DNS spoofing

services:
  router:
    image: ghcr.io/0nano/router-alpine:latest
    hostname: router1
    privileged: true
    environment: 
      NAT: 'true'
    networks:
      internet-access:
        ipv4_address: 10.0.3.254
        priority: 1000
      private-net:
        ipv4_address: 10.1.3.254
        priority: 200
  
  alpine-ssh:
    image: alpine-sshd:latest
    hostname: apline
    x-inscription: 10.1.3.2
    environment:
      GW: 10.1.3.254
      DNS: 10.1.3.4
    networks:
      private-net:
        ipv4_address: 10.1.3.2
  
  Kali:
    image: kali-web-simplify:latest
    hostname: kali
    x-inscription: 10.1.3.3
    environment:
      GW: 10.1.3.254
      DNS: 10.1.3.4
    networks:
      private-net:
        ipv4_address: 10.1.3.3

  dns:
    image: dns-spoofing
    hostname: dns
    x-inscription: 10.1.3.4
    environment:
      GW: 10.1.3.254
    networks:
      private-net:
        ipv4_address: 10.1.3.4

networks:
  internet-access:
    name: internet-access-scenario3
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.3.0/24
  private-net:
    name: private-net-scenario3
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.1.3.0/24
          